linters:
    flake8:
    eslint:
        config: './.eslintrc.json'
    csslint:
fixers:
    enable: true
  files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        - 'node_modules/*'
